services:
  webapp--database:
    image: postgres:14-alpine
    container_name: dong--webapp--database
    restart: always
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      PGDATA: /data/postgres
    volumes:
      - dong--webapp--database--data:/data/postgres
    ports:
      - 5432:5432

  webapp--web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dong--webapp--web
    restart: always
    env_file:
      - .env
    volumes:
      - dong--node_modules:/app/node_modules
    ports:
      - 80:3000
    depends_on:
      - webapp--database

volumes:
  dong--node_modules:
  dong--webapp--database--data:
